name: Renovate PR Fix
on:
  push:
    branches:
      - 'fix/**'
env:
  # Node.js
  NODE_VERSION: '17.7.0'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'
  NODE_AUTH_TOKEN: ${{ secrets.READ_ONLY_NPM_TOKEN }}
  COMMIT_USER_EMAIL: developer@triple-corp.com
  COMMIT_USER_NAME: triple-frontend[bot]

jobs:
  renovate-pr-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - run: npm install
      - run: npm run sync-deps

      - name: Commit and Push
        run: |
          git config --local user.email "${{ env.COMMIT_USER_EMAIL }}"
          git config --local user.name "${{ env.COMMIT_USER_NAME }}"
          git commit --amend --no-edit
          git push -f

  lint:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No lint required" '

  build:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required" '
